name = "HDR"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DrWatson = "2.18.0"
julia = "1.11.7"
