name = "HDR"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
MeanFieldGraph = "f3c20582-38a4-43ca-95fd-b3c95fb7ac78"
PointProcesses = "af0b7596-9bb0-472a-a012-63904f2b4c55"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
CairoMakie = "0.15"
Distributions = "0.25"
DrWatson = "2.19"
ExponentialUtilities = "1.27"
MeanFieldGraph = "0.2"
PointProcesses = "0.5"
Random = "1.11"
julia = "1.11"
